# Generated by Django 5.1.4 on 2024-12-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointement',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appointement',
            name='service',
            field=models.CharField(max_length=255),
        ),
    ]
